### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by SnesLover22** [JavaScythe/bnkr-pro#1]
how do i use this? Is there a secret button somewhere? Also made a fork of the old one how to use that?

**Comment by Cattn** [comment]
Bnkr-pro is not released yet, check the readme. It is being developed solo by @JavaScythe. If you need a Bunker download immediately, please use:

https://github.com/Math-Study/bunker-v1

or

https://github.com/JavaScythe/bunker

**Comment by SnesLover22** [comment]
yeah but i forked the last link you posted https://github.com/JavaScythe/bunker and idk what to do

**Comment by Cattn** [comment]
No need to fork, just head to https://github.com/JavaScythe/Bunker/releases/tag/v6-fixhost to download the latest release

**Comment by JavaScythe** [comment]
hola @SnesLover22
i am working on bunker pro
please leave star to make release sooner!!!!!
