### ISSUE TITLE
~~Developer Application~~

### ISSUE THREAD

**Issue by EpicPuppy613** [JavaScythe/bnkr-pro#2]
~~shut up you knew someone was bound to make one anyway~~

hey I code in JS and stuff

check my profile for stuff I made

this project seems cool I want to work with you

I know a bunch of node.js stuffs, ES6 modules and I also hate my school district IT department

yoooooooooooooooooooo it's another BSD student pog

**Comment by Cattn** [comment]
Hello, Cattn here owner of MSG in which the original bunker was created under, and (kinda this one he just uses us for clout lol) this one.

A few things:

BSD student?

Also, for more updates/easier way of talking with developers join math study

discord.gg/mathstudy


JavaScythe will be here soon

**Comment by EpicPuppy613** [comment]
No, it's not that

**Comment by JavaScythe** [comment]
Where in code is bsd???
Also send fr [object Object]#3827

**Comment by Cattn** [comment]
Oh, well either way it is a coincidence or probably his weird naming habits lol

**Comment by EpicPuppy613** [comment]
> Where in code is bsd??? Also send fr [object Object]#3827

`files/sysadmin.js`

**Comment by EpicPuppy613** [comment]
https://github.com/epicpuppy613/just-another-platformer

https://github.com/epicpuppy613/just-another-tower-defense

**Comment by EpicPuppy613** [comment]
also https://epicpuppy.dev but it got blocked by a bunch of filters so I moved most of the stuff to github.io

**Comment by EpicPuppy613** [comment]
uh my phone died :skull:

**Comment by EpicPuppy613** [comment]
just talk to me using this issue

**Comment by JavaScythe** [comment]
ok

**Comment by JavaScythe** [comment]
rejected, no longer accepting applications

**Comment by EpicPuppy613** [comment]
wtf why do you really hate your community that much

**Comment by EpicPuppy613** [comment]
I’m pretty sure bunker violates several laws

**Comment by EpicPuppy613** [comment]
I can and would very much report this GitHub and discord if it comes to that

**Comment by Nailington** [comment]
In no way does Bunker violate laws. All it does is use the file:// protocol with a redirect of about:blank. It is just a bunch of code to do things in a web browser.... Seems like a NORMAL thing to do......

**Comment by JavaScythe** [comment]
> wtf why do you really hate your community that much
@EpicPuppy613 
im sorry if it came off as rude but tbh im very busy and can't have additional management work

**Comment by Bro-11** [comment]
Do you need a community manager or something of that sort?

**Comment by JavaScythe** [comment]
not really, if you would like to discuss more options dm me at [object Object]#3827

**Comment by JavaScythe** [comment]
@Bro-11

**Comment by Bro-11** [comment]
Is your tag [object Object]? Just wanted to clarify

**Comment by Bro-11** [comment]
@JavaScythe

**Comment by JavaScythe** [comment]
yes

**Comment by Nailington** [comment]
`[object Object]#3827` is his exact tag
