### ISSUE TITLE
!Framer doesnt work

### ISSUE THREAD

**Issue by ezy-packs** [JavaScythe/bnkr-pro#21]
https://www.newgrounds.com
https://store.steampowered.com/
Refuse to connect idk if im not doing something right lol

**Comment by Nailington** [comment]
2 things:

1. iFramer is NOT a proxy (i dont think, havent used the new bunker)
2. some sites block iFrames

**Comment by JavaScythe** [comment]
Iframe attempts to embed the site you give it. This does not bypass any filtering, and some sites prevent themselves from being "iframed"
