### ISSUE TITLE
Developer Application

### ISSUE THREAD

**Issue by proudparrot2** [JavaScythe/bnkr-pro#4]
I am a knowledgeable dynamic JavaScript developer with 3 years of experience.
I've maintained the quick.js library for a few months, and the Art Class website and services since April. All of these use JavaScript throughout.

I also make proxies and Discord Bots using various NodeJS libraries, and have even dabbled in making one myself.
I hope you consider me, *again*, and thank you.

https://quick.js.org
https://liftoff.spacetechnology.net

**Comment by JavaScythe** [comment]
rejected, am no longer taking applications
