### ISSUE TITLE
Suggestion/Question

### ISSUE THREAD

**Issue by timmylol123** [JavaScythe/bnkr-pro#8]
Hello, I was just wondering if you could add n64 games to bunker pro? And also, is it going to be free?

**Comment by mathadventure1** [comment]
He may try and add them via EmulatorJS, or some other service as an addon. No promises

**Comment by JavaScythe** [comment]
a retro emulator will likely not be featured in the 3/14/23 release, but might come later on
(you can still embed retro emulator sites like https://cattn.github.io/gba/) (embedding will be supported in 3/14 release)

Of course, absolutely 100% free.
